exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "rft_cheques.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'npx --yes prettier@3.1.0 --write "$@"' --
        language: system
        types_or: [javascript, vue, scss, jsx, tsx]
        require_serial: false
        exclude: |
            (?x)^(
                rft_cheques/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                rft_cheques/templates/includes/.*|
                rft_cheques/public/js/lib/.*
            )$
      - id: eslint
        name: eslint
        entry: bash -c 'npx --yes eslint@8.44.0 --fix "$@"' --
        language: system
        types_or: [javascript]
        require_serial: false
        exclude: |
            (?x)^(
                rft_cheques/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                rft_cheques/templates/includes/.*|
                rft_cheques/public/js/lib/.*
            )$

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false